configured_endpoints: 95
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/nextbillion-ai%2Fnextbillion-sdk-1e5aa8d623200cf13b0f55738d28d0f716eb9c6bc21336bafe77c5e1e6f8515f.yml
openapi_spec_hash: 6af51daccd4c91b5d04f71c45dbc31d8
config_hash: 297ad5b2a79da3c4bae12d9bce4efcc7
